// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwkwGs_Du_7IKk2dyeUmqrm5kPYtMMrbE',
    appId: '1:814782831253:web:e4d3edee3387eb6d7d199c',
    messagingSenderId: '814782831253',
    projectId: 'school-app-d2798',
    authDomain: 'school-app-d2798.firebaseapp.com',
    databaseURL: 'https://school-app-d2798-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-d2798.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhLVWo42XVmXsP9tRiN0kpxmDLkW5jM94',
    appId: '1:814782831253:android:f51e7d4e8f65f0d07d199c',
    messagingSenderId: '814782831253',
    projectId: 'school-app-d2798',
    databaseURL: 'https://school-app-d2798-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-d2798.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Qy6vdsiQO6A6eAhrTromGltaLa53kM4',
    appId: '1:814782831253:ios:b220ae4fbf0728597d199c',
    messagingSenderId: '814782831253',
    projectId: 'school-app-d2798',
    databaseURL: 'https://school-app-d2798-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-d2798.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Qy6vdsiQO6A6eAhrTromGltaLa53kM4',
    appId: '1:814782831253:ios:b220ae4fbf0728597d199c',
    messagingSenderId: '814782831253',
    projectId: 'school-app-d2798',
    databaseURL: 'https://school-app-d2798-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-d2798.firebasestorage.app',
    iosBundleId: 'com.example.schoolApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwkwGs_Du_7IKk2dyeUmqrm5kPYtMMrbE',
    appId: '1:814782831253:web:e7f0e13b7e7140dd7d199c',
    messagingSenderId: '814782831253',
    projectId: 'school-app-d2798',
    authDomain: 'school-app-d2798.firebaseapp.com',
    databaseURL: 'https://school-app-d2798-default-rtdb.firebaseio.com',
    storageBucket: 'school-app-d2798.firebasestorage.app',
  );

}